import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Award, BadgeCheck, ChevronRight, HeartHandshake, Leaf, PackageCheck, ShieldCheck, Sprout, Star, Truck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { ProductCard } from "@/components/product-card";
import { SectionHeading } from "@/components/page-kit";
import { categories, faqs, heroImage, pantryImage, posts, products, services, storyImage, testimonials } from "@/lib/catalog";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "JANANI AGRO PRODUCTS — Pure Organic Harvest" }, { name: "description", content: "Premium organic rice, grains, pulses, spices, seeds and cold-pressed oils, responsibly sourced from trusted Indian farms." }, { property: "og:title", content: "JANANI AGRO PRODUCTS — Pure Organic Harvest" }, { property: "og:description", content: "Farm-traceable organic pantry essentials from Gujarat, India." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/" }] }),
  component: HomePage,
});

function HomePage() {
  return <>
    <section className="relative flex min-h-[760px] items-end overflow-hidden bg-forest text-primary-foreground lg:min-h-[calc(100vh-112px)]">
      <img src={heroImage} alt="Indian woman farmer standing in an organic wheat field at sunrise" width={1920} height={1088} className="absolute inset-0 h-full w-full object-cover object-[64%_center]" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,var(--forest)_0%,color-mix(in_oklab,var(--forest)_82%,transparent)_36%,transparent_72%)]" />
      <div className="relative mx-auto w-full max-w-7xl px-6 pb-20 pt-36 lg:pb-16"><div className="max-w-2xl animate-fade-up"><p className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.25em] text-brand-gold"><Sprout className="size-4" /> From soil to soul</p><h1 className="mt-6 text-5xl font-semibold leading-[1.05] sm:text-6xl lg:text-7xl">Pure organic harvest, shaped by nature.</h1><p className="mt-6 max-w-xl text-base leading-8 text-primary-foreground/80">Premium agricultural products delivered from trusted farms with purity, traceability and care in every pack.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild variant="gold" size="lg"><Link to="/products">Explore products <ArrowRight /></Link></Button><Button asChild variant="glass" size="lg"><Link to="/become-distributor">Become a distributor</Link></Button></div></div>
        <div className="mt-16 grid max-w-2xl grid-cols-2 gap-px overflow-hidden rounded-3xl border border-primary-foreground/20 bg-primary-foreground/15 backdrop-blur-md sm:grid-cols-4">{[["25+","Products"],["1,000+","Families"],["100+","Dealers"],["100%","Pure intent"]].map(([value,label]) => <div key={label} className="bg-forest/25 p-4"><strong className="font-display text-2xl text-brand-gold">{value}</strong><span className="mt-1 block text-[10px] uppercase tracking-wider text-primary-foreground/65">{label}</span></div>)}</div>
      </div>
    </section>
    <section className="border-b border-border bg-card"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-5 px-6 py-6 md:grid-cols-5">{[[Award,"Quality certified"],[BadgeCheck,"Organic range"],[Sprout,"Farm fresh"],[ShieldCheck,"Secure payments"],[Truck,"Fast delivery"]].map(([Icon,label]) => <div key={String(label)} className="flex items-center justify-center gap-2 text-xs font-semibold text-foreground/70"><Icon className="size-5 text-brand-leaf" />{String(label)}</div>)}</div></section>

    <section className="px-6 py-24"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2"><div className="relative"><img src={storyImage} alt="Farmers presenting a fresh wheat harvest" loading="lazy" width={1200} height={1408} className="aspect-[4/5] w-full rounded-[3rem] object-cover shadow-luxe" /><div className="absolute -bottom-6 -right-3 max-w-52 rounded-3xl bg-cream p-5 shadow-luxe sm:right-8"><strong className="font-display text-3xl text-primary">15 years</strong><span className="mt-1 block text-xs text-muted-foreground">of trusted farm relationships</span></div></div><div><SectionHeading eyebrow="Our roots" title="Good food begins with respect for the earth." copy="JANANI brings together traditional agricultural wisdom, responsible sourcing and uncompromising quality. We work closely with growers to preserve natural taste while building a more resilient food future." align="left" /><div className="mt-7 grid gap-5 sm:grid-cols-2"><div><h3 className="text-xl">Our vision</h3><p className="mt-2 text-sm leading-7 text-muted-foreground">A future where pure, responsible food is an everyday choice.</p></div><div><h3 className="text-xl">Our promise</h3><p className="mt-2 text-sm leading-7 text-muted-foreground">Honest origins, careful processing and dependable quality.</p></div></div><Button asChild variant="outline" className="mt-8"><Link to="/about">Discover our story <ArrowRight /></Link></Button></div></div></section>

    <section className="bg-secondary/70 px-6 py-24"><SectionHeading eyebrow="The organic pantry" title="Choose by harvest" copy="Everyday staples, thoughtfully cultivated and carefully packed." /><div className="mx-auto mt-12 grid max-w-7xl grid-cols-2 gap-4 md:grid-cols-5">{categories.map((cat, index) => <Link key={cat.slug} to="/categories/$slug" params={{ slug: cat.slug }} className={`group relative overflow-hidden rounded-3xl ${index === 0 || index === 5 ? "md:col-span-2" : ""}`}><img src={cat.image} alt={cat.name} loading="lazy" width={600} height={500} className="aspect-[4/5] h-full w-full object-cover transition duration-700 group-hover:scale-110"/><div className="absolute inset-0 bg-gradient-to-t from-forest/90 via-forest/10 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5 text-primary-foreground"><h3 className="text-xl font-semibold">{cat.name}</h3><span className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-brand-gold">Explore <ChevronRight className="size-3" /></span></div></Link>)}</div></section>

    <section className="px-6 py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Season's finest" title="Naturally loved essentials" copy="Our most-loved pantry staples, chosen for aroma, flavour and honest nourishment."/><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,8).map((product) => <ProductCard key={product.id} product={product} />)}</div><div className="mt-10 text-center"><Button asChild variant="outline"><Link to="/products">View all 24 products <ArrowRight /></Link></Button></div></div></section>

    <section className="overflow-hidden bg-forest px-6 py-24 text-primary-foreground"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-brand-gold">The Janani standard</p><h2 className="mt-4 text-4xl font-semibold sm:text-5xl">Nothing added. Nothing hidden.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-primary-foreground/70">From field selection to final seal, every step is designed to protect the crop’s natural character.</p><div className="mt-9 grid gap-4 sm:grid-cols-2">{[[Leaf,"Farm fresh"],[BadgeCheck,"Certified organic"],[PackageCheck,"Premium packaging"],[ShieldCheck,"Quality tested"],[Truck,"Reliable delivery"],[HeartHandshake,"Human support"]].map(([Icon,label]) => <div key={String(label)} className="flex items-center gap-3 rounded-2xl border border-primary-foreground/15 bg-primary-foreground/5 p-4"><Icon className="text-brand-gold"/><span className="text-sm font-semibold">{String(label)}</span></div>)}</div></div><img src={pantryImage} alt="A selection of organic rice, grains, pulses and spices" loading="lazy" width={1408} height={1056} className="rounded-[3rem] object-cover shadow-luxe"/></div></section>

    <section className="px-6 py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Partnership" title="Made for homes and growing businesses"/><div className="mt-12 grid gap-5 md:grid-cols-3">{services.map(([title,copy], index) => <div key={title} className="group rounded-3xl border border-border bg-card p-7 shadow-soft"><span className="text-5xl font-display text-brand-gold/55">0{index+1}</span><h3 className="mt-6 text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{copy}</p></div>)}</div></div></section>

    <section className="bg-secondary px-6 py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Farm to home" title="A shorter journey. A purer harvest."/><div className="mt-14 grid gap-8 md:grid-cols-5">{["Cultivation","Harvesting","Cleaning","Packaging","Delivery"].map((step,index) => <div key={step} className="relative text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-primary font-display text-xl text-primary-foreground shadow-brand">{index+1}</span><h3 className="mt-4 text-lg">{step}</h3><p className="mt-2 text-xs leading-6 text-muted-foreground">Care at every stage, with traceable standards.</p></div>)}</div></div></section>

    <section className="px-6 py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="From our community" title="Goodness people come back for"/><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{testimonials.slice(0,4).map(([name,city,review]) => <figure key={name} className="rounded-3xl border border-border bg-card p-6 shadow-soft"><div className="flex text-brand-gold">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-4 fill-current"/>)}</div><blockquote className="mt-5 text-sm leading-7 text-foreground/80">“{review}”</blockquote><figcaption className="mt-6"><strong className="block text-sm">{name}</strong><span className="text-xs text-muted-foreground">{city}</span></figcaption></figure>)}</div></div></section>

    <section className="px-6 pb-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Field notes" title="Stories for a more mindful pantry"/><div className="mt-12 grid gap-6 md:grid-cols-3">{posts.slice(0,3).map((post) => <article key={post.slug} className="overflow-hidden rounded-3xl bg-card shadow-soft"><img src={post.image} alt="" loading="lazy" width={700} height={500} className="aspect-[4/3] w-full object-cover"/><div className="p-6"><p className="text-xs text-brand-leaf">{post.date}</p><h3 className="mt-3 text-2xl font-semibold">{post.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{post.excerpt}</p><Button asChild variant="link" className="mt-3 px-0"><Link to="/blog/$slug" params={{slug:post.slug}}>Read the story <ArrowRight/></Link></Button></div></article>)}</div></div></section>

    <section className="bg-secondary/70 px-6 py-24"><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Questions, answered" title="Everything worth knowing" copy="Clear answers about sourcing, delivery, freshness and partnerships." align="left"/><Accordion type="single" collapsible>{faqs.map(([q,a],index)=><AccordionItem key={q} value={`faq-${index}`}><AccordionTrigger className="py-6 text-base">{q}</AccordionTrigger><AccordionContent className="leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>

    <section className="px-6 py-20"><div className="relative mx-auto max-w-7xl overflow-hidden rounded-[3rem] bg-primary px-7 py-14 text-primary-foreground sm:px-14"><div className="organic-grid absolute inset-0 opacity-15"/><div className="relative flex flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-gold">Personal assistance</p><h2 className="mt-3 max-w-2xl text-3xl sm:text-4xl">Let’s find the right harvest for your home or business.</h2></div><div className="flex flex-wrap gap-3"><Button asChild variant="gold"><a href="https://wa.me/919311416225">WhatsApp us</a></Button><Button asChild variant="glass"><a href="tel:+919311416225">Call +91 93114 16225</a></Button></div></div></div></section>
  </>;
}