import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Grid2X2, List, Search } from "lucide-react";
import { products, categories } from "@/lib/catalog";
import { ProductCard } from "@/components/product-card";
import { PageHero } from "@/components/page-kit";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/products/")({ head: () => ({ meta: [{ title: "Organic Products — JANANI" }, { name: "description", content: "Shop organic grains, pulses, spices, oils, seeds and pantry essentials." }, { property: "og:title", content: "Organic Products — JANANI" }, { property: "og:description", content: "Shop farm-traceable organic pantry essentials." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ProductsPage });
function ProductsPage(){ const [query,setQuery]=useState(""); const [category,setCategory]=useState("All"); const [sort,setSort]=useState("featured"); const [list,setList]=useState(false); const visible=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:a.id-b.id),[query,category,sort]); return <><PageHero eyebrow="The JANANI pantry" title="Pure ingredients for everyday rituals." copy="Explore consciously sourced staples with natural flavour, dependable quality and transparent origins."/><div className="mx-auto max-w-7xl px-6 py-14"><div className="grid gap-8 lg:grid-cols-[240px_1fr]"><aside><h2 className="text-xl">Filter the harvest</h2><div className="mt-5 grid gap-2">{["All",...categories.map(c=>c.name)].map(c=><button key={c} onClick={()=>setCategory(c)} className={`rounded-xl px-3 py-2 text-left text-sm transition ${category===c?"bg-primary text-primary-foreground":"hover:bg-secondary"}`}>{c}</button>)}</div></aside><div><div className="mb-7 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><label className="relative"><Search className="absolute left-4 top-3.5 size-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the pantry" className="h-11 w-full rounded-full border border-input bg-card pl-11 pr-4 text-sm outline-none focus:border-primary"/></label><select value={sort} onChange={e=>setSort(e.target.value)} className="h-11 rounded-full border border-input bg-card px-4 text-sm"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select><div className="flex"><Button variant={!list?"default":"outline"} size="icon" onClick={()=>setList(false)} aria-label="Grid view"><Grid2X2/></Button><Button variant={list?"default":"outline"} size="icon" onClick={()=>setList(true)} aria-label="List view"><List/></Button></div></div><p className="mb-5 text-sm text-muted-foreground">{visible.length} products</p><div className={list?"grid gap-5":"grid gap-5 sm:grid-cols-2 xl:grid-cols-3"}>{visible.map(p=><ProductCard key={p.id} product={p} list={list}/>)}</div></div></div></div></> }